### ISSUE TITLE
Stuck due to unauthorized access to endpoints. 

### ISSUE THREAD

**Issue by bluerid** [caio-ribeiro-pereira/building-apis-with-nodejs#10]
![screen](https://cloud.githubusercontent.com/assets/968650/23821669/11eb2214-0660-11e7-91ab-19dc1ad317db.png)
I followed the steps laid out in the pdf and used passport js lib for authenticating the endpoints. However, I am stuck after I placed the _app.auth.authenticate()_ in _route.all()_ middleware. It's showing me ### **Unauthorized** as it should. How do I use the web token in _Postman_ to view the tasks list? I am getting response from _/token/_ route, when I am providing a jsonified email and password. Not sure how to resolve this issue. When I remove _app.auth.authenticate()_ I am able to see the task list (or create).

       app.route('/tasks')
		.all(app.auth.authenticate())
		.get((req, res)	=> {
			//Tasks: List tasks.
			Tasks.findAll({
				where: { user_id: req.user.id }
			}).then(
				result => res.json(result)
			).catch(error => {
				res.status(412).json({msg:error.message})
			});
		})
		.post((req, res) => {
			//Save Tasks: Save Task.
			req.body.user_id = req.user.id;
			Tasks.create(req.body).then(
				result => res.json(result)
			).catch(error => {
				res.status(412).json({msg:error.message})
			});
		});

**Comment by bluerid** [comment]
Missed the JWT in front of token. It has to be submitted in the following format:
**JWT {header.claim.signature}**.

**Comment by caio-ribeiro-pereira** [comment]
The correct header is:

Authorization = JWT {TOKEN}

**Comment by bluerid** [comment]
Yes, I figured that out. A JWT TOKEN usually is in this format: _header.claim.signature_ as you know.

**Comment by pranjalnadhani** [comment]
Change the header _key_ to **Authorization** and _value_ to **JWT {your token}**

That would work :)
