### ISSUE TITLE
npm test not working

### ISSUE THREAD

**Issue by nitinmukesh** [caio-ribeiro-pereira/building-apis-with-nodejs#11]
Hello,

many thanks for the tutorial, this is very very helpful for a newbie like me. I am able to follow the complete code and able to make it run. The only issue I am facing is related to test.

I downloaded the repository and installed all packages.
entered the following command
npm test

```
D:\XAMPP\htdocs\nodewebservice\building-apis-with-nodejs-master\ntask-api>npm test

> ntask-api@1.0.0 test D:\XAMPP\htdocs\nodewebservice\building-apis-with-nodejs-master\ntask-api
> SET NODE_ENV=test mocha test/**/*.js

D:\XAMPP\htdocs\nodewebservice\building-apis-with-nodejs-master\ntask-api>
```

There is no test executed. Please help me solve this,

**Comment by caio-ribeiro-pereira** [comment]
Hi, I think it will be better you install Cygwin environment to enable a bash terminal for you, because you will run all commands by following the examples of the book, instead trying to adapt for windows prompt.

**Comment by nitinmukesh** [comment]
Thank you caio-ribeiro-pereira, I will try this.

**Comment by caio-ribeiro-pereira** [comment]
You're welcome!
