### ISSUE TITLE
Request to include production and process monitor in tutorial

### ISSUE THREAD

**Issue by nitinmukesh** [caio-ribeiro-pereira/building-apis-with-nodejs#12]
Hello caio-ribeiro-pereira,

I am impressed the way the whole code and documentation is put together. It is easy to follow even for a beginner like me.

Kindly include the following in tutorial
1. Creating production build (If the api code is going to be deployed on customer end it should be obsfucated) and deployment (maybe using docker)
2. using process monitoring tool like PM2 (I tried but it does not work with the code)

**Comment by caio-ribeiro-pereira** [comment]
Hi, this is something which I could write in a specifical book, because there are a lot of deployment solution, but thank you for this feedback, I will note here for my future book :)
