### ISSUE TITLE
Content Security

### ISSUE THREAD

**Issue by ghost** [caio-ribeiro-pereira/building-apis-with-nodejs#14]
iam having following error when i hit  /tasks URL

AfterContent Security Policy: The page’s settings blocked the loading of a resource at self (“default-src http://localhost:3000”)

**Comment by caio-ribeiro-pereira** [comment]
This is something related to your browser, if you are using HTTPS server, you must allow this address into your browser, because there are some browsers which by default, blocks any https from localhost address.
