### ISSUE TITLE
Chapter 8 - Authenticated User Token; Test Fails

### ISSUE THREAD

**Issue by jeffnyman** [caio-ribeiro-pereira/building-apis-with-nodejs#18]
If you follow the book through to the end up chapter 8, the following test seems to always fail:

    Routes: Token
        POST /token
            status 200
                1) returns authenticated user token

It always says:

    Uncaught AssertionError: expected {} to contain key 'token'
      + expected - actual

      -[]
      +[
      +  "token"
      +]

That said, you get this by following the book code exactly. Checking out the current repo will not show that issue because it contains all changes. I've been doing a branch per chapter, which is how I'm able to isolate certain issues.

**Comment by Orinameh** [comment]
Inside models/users.js, uncomment isPassword inside the class method and go to routes/token.js, replace if(Users.isPassword(....)) with if(bcrypt.compareSync(password, user.password) {...}. Make sure you import bcrypt at the top of the file. That worked for me

**Comment by TomsCodeVault** [comment]
Thanks Orinameh! The other thing that's happening to me at that point is that in the output the line "NTask API - Port 3000" is being output to the console right after "POST /token status 200" every time. It seems that the server gets started again every time the first test runs. If I comment out the first test, it happens after the second test and prints out right under the "status 401" line. Any idea why that's happening?
Here's a clip from my console:

``  Routes: Index
    GET /
      √ returns the API status

  Routes: Token
    POST /token
      status 200
NTask API - Port 3000
        √ returns authenticated user token
      status 401
        √ throws error when password is incorrect
        √ throws error when email not exist
        √ throws error when email and password are blank

>

**Comment by TomsCodeVault** [comment]
I think I got to the bottom of this. I'm running windows so in the test script in the package.json file, I need to use "SET" before  NODE_ENV=test mocha test/**/*.js and an ampersand between test and mocha, like this: "SET NODE_ENV=test & mocha test/**/*.js" When I do that, NODE_ENV is set to "test " with a trailing space. To fix it, I changed the script to:  "SET NODE_ENV=test& mocha test/**/*.js"
Perhaps there is a better way to do this. If so, I'd like to know.

I hope this helps somebody.

**Comment by koalapenguins** [comment]
i also have the same issue, not even changing if(Users.isPassword(....)) with if(bcrypt.compareSync(password, user.password) {...} is working

even directly downloading the github code of chapter 8 has this problem

**Comment by koalapenguins** [comment]
although, if one directly downloads chapter 9, using the command:

`npm test --dev`

tested the chapter successfully (as opposed to only `npm test`)

it needed the --dev flag for me

hope it helps someone too

**Comment by Tobias-Doerner** [comment]
Had the same problem as @jeffnyman reason was that I've used a higher version of sequelize then mentioned in the book. Therefor the isPassword method defined in models/users.js is not recognized and so the check of the encrypted password fails which lets the test fail. If I'm using version 3 of sequelize everything is working fine. If you want to use version 4 of sequelize you have to do some changes to your code see [Sequelize Manual](http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html#breaking-changes)

For example remove in model/users.js
`classMethods: {
      associate: models => {
        Users.hasMany(models.Tasks);
      },
      isPassword: (encodedPassword, password) => {
        return bcrypt.compareSync(password, encodedPassword);
      }
    }`

and add before the return statement this block. For further infos the Sequelize Manual is telling you everything you need.

`Users.associate = models => {
    Users.hasMany(models.Tasks);
  };
  Users.prototype.isPassword = function (encodedPassword, password) {
    return bcrypt.compareSync(password, encodedPassword);
  };`

**Comment by caio-ribeiro-pereira** [comment]
Guys, many changes happened in the Sequelize module, unfortunatelly I can't update the book, so you have to use the right (old) versions of all modules in the book to the project runs fine, thank you!
