### ISSUE TITLE
User_id column is missing

### ISSUE THREAD

**Issue by Orinameh** [caio-ribeiro-pereira/building-apis-with-nodejs#19]
Nice tutorial once again. Seems you missed the user_id column in the Task table. I tried to add it but still my test is still failing. Will keep on trying though

**Comment by hieudang59** [comment]
I got the same issue. Does Anyone know?

**Comment by gaboAcosta** [comment]
Wow! I am extremely disappointed! Not only has the author missed a huge breaking change in that, he has also left everyone in this repository left hanging.

Guys, just change your migration to have the said column, delete your database and run the app again and you should be fine!

**Comment by caio-ribeiro-pereira** [comment]
Really really sorry guys, unfortunatelly I didn't receive any notifications from github and I though this repository was dead.

Only today I start to take a look in all of my repositories again to answer some issues, really sorry.

And thank you @gaboAcosta for your feedback and for your solution, you are right, just reset the database when run all migrations again and will be fine
