### ISSUE TITLE
Where does app.db comes from?

### ISSUE THREAD

**Issue by forethoughtde** [caio-ribeiro-pereira/building-apis-with-nodejs#23]
Can I please know where does app.db comes from?

```
app.db.sync().done(() => {
        app.listen(app.get('port'), ()=>{
            return console.log(`NTask API - Port ${app.get('port')}`);
        });
    });
```

Later, it got switched to app.db.sequelize.

```
app.db.sequelize.sync().done(() => {
        app.listen(app.get('port'), ()=>{
            return console.log(`NTask API - Port ${app.get('port')}`);
        });
    });
```

**Comment by caio-ribeiro-pereira** [comment]
Hi @forethoughtde ...

In the `index.js` we have this code:

``` javascript
import express from "express";
import consign from "consign";

const app = express();

consign({verbose: false})
  .include("libs/config.js")
  .then("db.js")
  .then("auth.js")
  .then("libs/middlewares.js")
  .then("routes")
  .then("libs/boot.js")
  .into(app);

module.exports = app;
```

The consign module is responsible to load the modules and after load them, each file will be attached into `app` variable, so when consign runs `.then('db.js')`, it will be added `app.db`, routes folder will be added each file into `app.routes.{routes_files}`, and etc

**Comment by forethoughtde** [comment]
Thank you very much! I understand it now. I cannot understand about below code:

```
classMethods : {
            associate : (model)=>{
                Tasks.belongsTo(model.Users)
            }
        }
```

What does this do?

**Comment by caio-ribeiro-pereira** [comment]
@forethoughtde `=>` is called as Arrow Function, is a new way to create functions in JavaScript, this link will help you learn more about it:
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by forethoughtde** [comment]
Thank you!

**Comment by caio-ribeiro-pereira** [comment]
You're welcome!
