### ISSUE TITLE
Hoes does express instance is accessible inside routes directory?

### ISSUE THREAD

**Issue by forethoughtde** [caio-ribeiro-pereira/building-apis-with-nodejs#24]
I am just curious, how does express instance is accessible inside routes directory?

```
module.exports = app =>{
    app.get('/', (req, res)=>{
        res.json({'status': 'NTask API'});
    });
};
```

_app_ variable is defined in index.js file in root directory of the project but we use app in routes directory in both routes. Can you please explain this? Thanks in advance.

**Comment by caio-ribeiro-pereira** [comment]
This is the way consign module works.
To learn more about it, I suggest you read this doc: https://www.npmjs.com/package/consign
