### ISSUE TITLE
Page 7, npm fact error!

### ISSUE THREAD

**Issue by amandeepmittal** [caio-ribeiro-pereira/building-apis-with-nodejs#4]
On page 7 under the section, _What does NPM do?_, you wrote: "+149 million downloads are made daily and +3.4 million downloads are made monthly." 
Shouldn't _3.4 million_ i be _**3.4 billion**_?

**Comment by caio-ribeiro-pereira** [comment]
Yeah, you are right! Thank you for the feedback, I'll update it soon

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com

**Comment by amandeepmittal** [comment]
Btw I like your book, it's covers API in-depth.

**Comment by caio-ribeiro-pereira** [comment]
Thank you! Would you like to write a testimonials about my book?

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com

**Comment by amandeepmittal** [comment]
Yes, sure.

**Comment by caio-ribeiro-pereira** [comment]
Please answer these fields:

Name:
Title:
Testimonial: (max 400 chars)
Photo url:

Regards,
Caio Ribeiro Pereira
About: http://crpwebdev.com
