### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by sdemurjian** [caio-ribeiro-pereira/building-apis-with-nodejs#6]

**Comment by caio-ribeiro-pereira** [comment]
?

**Comment by sdemurjian** [comment]
what license is this code under?

**Comment by caio-ribeiro-pereira** [comment]
This project is used for study purposes, and all code has been using in my ebook: https://leanpub.com/building-apis-with-nodejs
So there is no need for a license, just feel free to copy and use all codes in your own projects (even commercial ones)

**Comment by sdemurjian** [comment]
Thanks! just wanted to make sure

**Comment by caio-ribeiro-pereira** [comment]
:)
